Traceback (most recent call last):
  File "/Users/keanl/Desktop/Computer_Science/Comp_775/project/Comp775Project/train_segment_afa.py", line 36, in <module>
    main()
  File "/Users/keanl/Desktop/Computer_Science/Comp_775/project/Comp775Project/train_segment_afa.py", line 33, in main
    unet_model = tf.keras.models.load_model(unet_artifact_dir)((features, targets))
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/tensorflow/python/framework/type_spec.py", line 434, in _deserialize
    return cls(*serialization)  # pytype: disable=not-instantiable  # trace-all-classes
TypeError: __init__() takes from 2 to 4 positional arguments but 5 were given
Traceback (most recent call last):
  File "/Users/keanl/Desktop/Computer_Science/Comp_775/project/Comp775Project/train_segment_afa.py", line 36, in <module>
    main()
  File "/Users/keanl/Desktop/Computer_Science/Comp_775/project/Comp775Project/train_segment_afa.py", line 33, in main
    unet_model = tf.keras.models.load_model(unet_artifact_dir)((features, targets))
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/tensorflow/python/framework/type_spec.py", line 434, in _deserialize
    return cls(*serialization)  # pytype: disable=not-instantiable  # trace-all-classes
TypeError: __init__() takes from 2 to 4 positional arguments but 5 were given